/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OldHomeRouteImport } from './routes/old-home'
import { Route as MobileInternRouteImport } from './routes/mobile-intern'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as FullstackDevRouteImport } from './routes/fullstack-dev'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as vendorPanelVendorRouteImport } from './routes/(vendor-panel)/_vendor'
import { Route as authUnauthorizedRouteImport } from './routes/(auth)/unauthorized'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AdminVendorsIndexRouteImport } from './routes/admin/vendors/index'
import { Route as AdminTransactionsIndexRouteImport } from './routes/admin/transactions/index'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students/index'
import { Route as AdminCmsIndexRouteImport } from './routes/admin/cms/index'
import { Route as AdminTransactionsIdRouteImport } from './routes/admin/transactions/$id'
import { Route as vendorPanelVendorPinRouteImport } from './routes/(vendor-panel)/_vendor.pin'
import { Route as vendorPanelVendorDashboardRouteImport } from './routes/(vendor-panel)/_vendor.dashboard'
import { Route as vendorPanelVendorContactUsRouteImport } from './routes/(vendor-panel)/_vendor.contact-us'
import { Route as AdminCmsUniversitiesIndexRouteImport } from './routes/admin/cms/universities/index'
import { Route as AdminCmsTrendingOffersIndexRouteImport } from './routes/admin/cms/trending-offers/index'
import { Route as AdminCmsCategoriesIndexRouteImport } from './routes/admin/cms/categories/index'
import { Route as AdminCmsBrandsIndexRouteImport } from './routes/admin/cms/brands/index'
import { Route as AdminCmsBannersIndexRouteImport } from './routes/admin/cms/banners/index'
import { Route as AdminVendorsVendorIdSettingsRouteImport } from './routes/admin/vendors/$vendorId.settings'
import { Route as AdminStudentsStudentIdSettingsRouteImport } from './routes/admin/students/$studentId.settings'
import { Route as AdminCmsUniversitiesAddRouteImport } from './routes/admin/cms/universities/add'
import { Route as AdminCmsCategoriesCategoryIdRouteImport } from './routes/admin/cms/categories/$categoryId'
import { Route as AdminCmsBrandsAddRouteImport } from './routes/admin/cms/brands/add'
import { Route as AdminCmsBannersAddRouteImport } from './routes/admin/cms/banners/add'
import { Route as AdminVendorsVendorIdSettingsIndexRouteImport } from './routes/admin/vendors/$vendorId.settings.index'
import { Route as AdminVendorsVendorIdSettingsOffersRouteImport } from './routes/admin/vendors/$vendorId.settings.offers'
import { Route as AdminVendorsVendorIdSettingsBrandingRouteImport } from './routes/admin/vendors/$vendorId.settings.branding'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OldHomeRoute = OldHomeRouteImport.update({
  id: '/old-home',
  path: '/old-home',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileInternRoute = MobileInternRouteImport.update({
  id: '/mobile-intern',
  path: '/mobile-intern',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const FullstackDevRoute = FullstackDevRouteImport.update({
  id: '/fullstack-dev',
  path: '/fullstack-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const vendorPanelVendorRoute = vendorPanelVendorRouteImport.update({
  id: '/(vendor-panel)/_vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const authUnauthorizedRoute = authUnauthorizedRouteImport.update({
  id: '/(auth)/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport
  .update({
    id: '/(auth)/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/login.lazy').then((d) => d.Route))
const AdminVendorsIndexRoute = AdminVendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/vendors/index.lazy').then((d) => d.Route),
)
const AdminTransactionsIndexRoute = AdminTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/transactions/index.lazy').then((d) => d.Route),
)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/students/index.lazy').then((d) => d.Route),
)
const AdminCmsIndexRoute = AdminCmsIndexRouteImport.update({
  id: '/cms/',
  path: '/cms/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsIdRoute = AdminTransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/transactions/$id.lazy').then((d) => d.Route),
)
const vendorPanelVendorPinRoute = vendorPanelVendorPinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => vendorPanelVendorRoute,
} as any)
const vendorPanelVendorDashboardRoute =
  vendorPanelVendorDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => vendorPanelVendorRoute,
  } as any)
const vendorPanelVendorContactUsRoute =
  vendorPanelVendorContactUsRouteImport.update({
    id: '/contact-us',
    path: '/contact-us',
    getParentRoute: () => vendorPanelVendorRoute,
  } as any)
const AdminCmsUniversitiesIndexRoute =
  AdminCmsUniversitiesIndexRouteImport.update({
    id: '/cms/universities/',
    path: '/cms/universities/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/cms/universities/index.lazy').then((d) => d.Route),
  )
const AdminCmsTrendingOffersIndexRoute =
  AdminCmsTrendingOffersIndexRouteImport.update({
    id: '/cms/trending-offers/',
    path: '/cms/trending-offers/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin/cms/trending-offers/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminCmsCategoriesIndexRoute = AdminCmsCategoriesIndexRouteImport.update({
  id: '/cms/categories/',
  path: '/cms/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsBrandsIndexRoute = AdminCmsBrandsIndexRouteImport.update({
  id: '/cms/brands/',
  path: '/cms/brands/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/cms/brands/index.lazy').then((d) => d.Route),
)
const AdminCmsBannersIndexRoute = AdminCmsBannersIndexRouteImport.update({
  id: '/cms/banners/',
  path: '/cms/banners/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin/cms/banners/index.lazy').then((d) => d.Route),
)
const AdminVendorsVendorIdSettingsRoute =
  AdminVendorsVendorIdSettingsRouteImport.update({
    id: '/vendors/$vendorId/settings',
    path: '/vendors/$vendorId/settings',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminStudentsStudentIdSettingsRoute =
  AdminStudentsStudentIdSettingsRouteImport.update({
    id: '/students/$studentId/settings',
    path: '/students/$studentId/settings',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCmsUniversitiesAddRoute = AdminCmsUniversitiesAddRouteImport.update({
  id: '/cms/universities/add',
  path: '/cms/universities/add',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsCategoriesCategoryIdRoute =
  AdminCmsCategoriesCategoryIdRouteImport.update({
    id: '/cms/categories/$categoryId',
    path: '/cms/categories/$categoryId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCmsBrandsAddRoute = AdminCmsBrandsAddRouteImport.update({
  id: '/cms/brands/add',
  path: '/cms/brands/add',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsBannersAddRoute = AdminCmsBannersAddRouteImport.update({
  id: '/cms/banners/add',
  path: '/cms/banners/add',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendorsVendorIdSettingsIndexRoute =
  AdminVendorsVendorIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminVendorsVendorIdSettingsRoute,
  } as any)
const AdminVendorsVendorIdSettingsOffersRoute =
  AdminVendorsVendorIdSettingsOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AdminVendorsVendorIdSettingsRoute,
  } as any)
const AdminVendorsVendorIdSettingsBrandingRoute =
  AdminVendorsVendorIdSettingsBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AdminVendorsVendorIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/fullstack-dev': typeof FullstackDevRoute
  '/internships': typeof InternshipsRoute
  '/mobile-intern': typeof MobileInternRoute
  '/old-home': typeof OldHomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/login': typeof authLoginRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/contact-us': typeof vendorPanelVendorContactUsRoute
  '/dashboard': typeof vendorPanelVendorDashboardRoute
  '/pin': typeof vendorPanelVendorPinRoute
  '/admin/transactions/$id': typeof AdminTransactionsIdRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/transactions/': typeof AdminTransactionsIndexRoute
  '/admin/vendors/': typeof AdminVendorsIndexRoute
  '/admin/cms/banners/add': typeof AdminCmsBannersAddRoute
  '/admin/cms/brands/add': typeof AdminCmsBrandsAddRoute
  '/admin/cms/categories/$categoryId': typeof AdminCmsCategoriesCategoryIdRoute
  '/admin/cms/universities/add': typeof AdminCmsUniversitiesAddRoute
  '/admin/students/$studentId/settings': typeof AdminStudentsStudentIdSettingsRoute
  '/admin/vendors/$vendorId/settings': typeof AdminVendorsVendorIdSettingsRouteWithChildren
  '/admin/cms/banners/': typeof AdminCmsBannersIndexRoute
  '/admin/cms/brands/': typeof AdminCmsBrandsIndexRoute
  '/admin/cms/categories/': typeof AdminCmsCategoriesIndexRoute
  '/admin/cms/trending-offers/': typeof AdminCmsTrendingOffersIndexRoute
  '/admin/cms/universities/': typeof AdminCmsUniversitiesIndexRoute
  '/admin/vendors/$vendorId/settings/branding': typeof AdminVendorsVendorIdSettingsBrandingRoute
  '/admin/vendors/$vendorId/settings/offers': typeof AdminVendorsVendorIdSettingsOffersRoute
  '/admin/vendors/$vendorId/settings/': typeof AdminVendorsVendorIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/fullstack-dev': typeof FullstackDevRoute
  '/internships': typeof InternshipsRoute
  '/mobile-intern': typeof MobileInternRoute
  '/old-home': typeof OldHomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/login': typeof authLoginRoute
  '/unauthorized': typeof authUnauthorizedRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/contact-us': typeof vendorPanelVendorContactUsRoute
  '/dashboard': typeof vendorPanelVendorDashboardRoute
  '/pin': typeof vendorPanelVendorPinRoute
  '/admin/transactions/$id': typeof AdminTransactionsIdRoute
  '/admin/cms': typeof AdminCmsIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/admin/transactions': typeof AdminTransactionsIndexRoute
  '/admin/vendors': typeof AdminVendorsIndexRoute
  '/admin/cms/banners/add': typeof AdminCmsBannersAddRoute
  '/admin/cms/brands/add': typeof AdminCmsBrandsAddRoute
  '/admin/cms/categories/$categoryId': typeof AdminCmsCategoriesCategoryIdRoute
  '/admin/cms/universities/add': typeof AdminCmsUniversitiesAddRoute
  '/admin/students/$studentId/settings': typeof AdminStudentsStudentIdSettingsRoute
  '/admin/cms/banners': typeof AdminCmsBannersIndexRoute
  '/admin/cms/brands': typeof AdminCmsBrandsIndexRoute
  '/admin/cms/categories': typeof AdminCmsCategoriesIndexRoute
  '/admin/cms/trending-offers': typeof AdminCmsTrendingOffersIndexRoute
  '/admin/cms/universities': typeof AdminCmsUniversitiesIndexRoute
  '/admin/vendors/$vendorId/settings/branding': typeof AdminVendorsVendorIdSettingsBrandingRoute
  '/admin/vendors/$vendorId/settings/offers': typeof AdminVendorsVendorIdSettingsOffersRoute
  '/admin/vendors/$vendorId/settings': typeof AdminVendorsVendorIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRoute
  '/fullstack-dev': typeof FullstackDevRoute
  '/internships': typeof InternshipsRoute
  '/mobile-intern': typeof MobileInternRoute
  '/old-home': typeof OldHomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/unauthorized': typeof authUnauthorizedRoute
  '/(vendor-panel)/_vendor': typeof vendorPanelVendorRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/(vendor-panel)/_vendor/contact-us': typeof vendorPanelVendorContactUsRoute
  '/(vendor-panel)/_vendor/dashboard': typeof vendorPanelVendorDashboardRoute
  '/(vendor-panel)/_vendor/pin': typeof vendorPanelVendorPinRoute
  '/admin/transactions/$id': typeof AdminTransactionsIdRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/transactions/': typeof AdminTransactionsIndexRoute
  '/admin/vendors/': typeof AdminVendorsIndexRoute
  '/admin/cms/banners/add': typeof AdminCmsBannersAddRoute
  '/admin/cms/brands/add': typeof AdminCmsBrandsAddRoute
  '/admin/cms/categories/$categoryId': typeof AdminCmsCategoriesCategoryIdRoute
  '/admin/cms/universities/add': typeof AdminCmsUniversitiesAddRoute
  '/admin/students/$studentId/settings': typeof AdminStudentsStudentIdSettingsRoute
  '/admin/vendors/$vendorId/settings': typeof AdminVendorsVendorIdSettingsRouteWithChildren
  '/admin/cms/banners/': typeof AdminCmsBannersIndexRoute
  '/admin/cms/brands/': typeof AdminCmsBrandsIndexRoute
  '/admin/cms/categories/': typeof AdminCmsCategoriesIndexRoute
  '/admin/cms/trending-offers/': typeof AdminCmsTrendingOffersIndexRoute
  '/admin/cms/universities/': typeof AdminCmsUniversitiesIndexRoute
  '/admin/vendors/$vendorId/settings/branding': typeof AdminVendorsVendorIdSettingsBrandingRoute
  '/admin/vendors/$vendorId/settings/offers': typeof AdminVendorsVendorIdSettingsOffersRoute
  '/admin/vendors/$vendorId/settings/': typeof AdminVendorsVendorIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/fullstack-dev'
    | '/internships'
    | '/mobile-intern'
    | '/old-home'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/login'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/admin/'
    | '/contact-us'
    | '/dashboard'
    | '/pin'
    | '/admin/transactions/$id'
    | '/admin/cms/'
    | '/admin/students/'
    | '/admin/transactions/'
    | '/admin/vendors/'
    | '/admin/cms/banners/add'
    | '/admin/cms/brands/add'
    | '/admin/cms/categories/$categoryId'
    | '/admin/cms/universities/add'
    | '/admin/students/$studentId/settings'
    | '/admin/vendors/$vendorId/settings'
    | '/admin/cms/banners/'
    | '/admin/cms/brands/'
    | '/admin/cms/categories/'
    | '/admin/cms/trending-offers/'
    | '/admin/cms/universities/'
    | '/admin/vendors/$vendorId/settings/branding'
    | '/admin/vendors/$vendorId/settings/offers'
    | '/admin/vendors/$vendorId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/fullstack-dev'
    | '/internships'
    | '/mobile-intern'
    | '/old-home'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/login'
    | '/unauthorized'
    | '/admin/dashboard'
    | '/admin'
    | '/contact-us'
    | '/dashboard'
    | '/pin'
    | '/admin/transactions/$id'
    | '/admin/cms'
    | '/admin/students'
    | '/admin/transactions'
    | '/admin/vendors'
    | '/admin/cms/banners/add'
    | '/admin/cms/brands/add'
    | '/admin/cms/categories/$categoryId'
    | '/admin/cms/universities/add'
    | '/admin/students/$studentId/settings'
    | '/admin/cms/banners'
    | '/admin/cms/brands'
    | '/admin/cms/categories'
    | '/admin/cms/trending-offers'
    | '/admin/cms/universities'
    | '/admin/vendors/$vendorId/settings/branding'
    | '/admin/vendors/$vendorId/settings/offers'
    | '/admin/vendors/$vendorId/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/fullstack-dev'
    | '/internships'
    | '/mobile-intern'
    | '/old-home'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/(auth)/login'
    | '/(auth)/unauthorized'
    | '/(vendor-panel)/_vendor'
    | '/admin/dashboard'
    | '/admin/'
    | '/(vendor-panel)/_vendor/contact-us'
    | '/(vendor-panel)/_vendor/dashboard'
    | '/(vendor-panel)/_vendor/pin'
    | '/admin/transactions/$id'
    | '/admin/cms/'
    | '/admin/students/'
    | '/admin/transactions/'
    | '/admin/vendors/'
    | '/admin/cms/banners/add'
    | '/admin/cms/brands/add'
    | '/admin/cms/categories/$categoryId'
    | '/admin/cms/universities/add'
    | '/admin/students/$studentId/settings'
    | '/admin/vendors/$vendorId/settings'
    | '/admin/cms/banners/'
    | '/admin/cms/brands/'
    | '/admin/cms/categories/'
    | '/admin/cms/trending-offers/'
    | '/admin/cms/universities/'
    | '/admin/vendors/$vendorId/settings/branding'
    | '/admin/vendors/$vendorId/settings/offers'
    | '/admin/vendors/$vendorId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRoute
  FullstackDevRoute: typeof FullstackDevRoute
  InternshipsRoute: typeof InternshipsRoute
  MobileInternRoute: typeof MobileInternRoute
  OldHomeRoute: typeof OldHomeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  authLoginRoute: typeof authLoginRoute
  authUnauthorizedRoute: typeof authUnauthorizedRoute
  vendorPanelVendorRoute: typeof vendorPanelVendorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/old-home': {
      id: '/old-home'
      path: '/old-home'
      fullPath: '/old-home'
      preLoaderRoute: typeof OldHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-intern': {
      id: '/mobile-intern'
      path: '/mobile-intern'
      fullPath: '/mobile-intern'
      preLoaderRoute: typeof MobileInternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fullstack-dev': {
      id: '/fullstack-dev'
      path: '/fullstack-dev'
      fullPath: '/fullstack-dev'
      preLoaderRoute: typeof FullstackDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(vendor-panel)/_vendor': {
      id: '/(vendor-panel)/_vendor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof vendorPanelVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/unauthorized': {
      id: '/(auth)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof authUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors/': {
      id: '/admin/vendors/'
      path: '/vendors'
      fullPath: '/admin/vendors/'
      preLoaderRoute: typeof AdminVendorsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions/': {
      id: '/admin/transactions/'
      path: '/transactions'
      fullPath: '/admin/transactions/'
      preLoaderRoute: typeof AdminTransactionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/': {
      id: '/admin/cms/'
      path: '/cms'
      fullPath: '/admin/cms/'
      preLoaderRoute: typeof AdminCmsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions/$id': {
      id: '/admin/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/admin/transactions/$id'
      preLoaderRoute: typeof AdminTransactionsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(vendor-panel)/_vendor/pin': {
      id: '/(vendor-panel)/_vendor/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof vendorPanelVendorPinRouteImport
      parentRoute: typeof vendorPanelVendorRoute
    }
    '/(vendor-panel)/_vendor/dashboard': {
      id: '/(vendor-panel)/_vendor/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof vendorPanelVendorDashboardRouteImport
      parentRoute: typeof vendorPanelVendorRoute
    }
    '/(vendor-panel)/_vendor/contact-us': {
      id: '/(vendor-panel)/_vendor/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof vendorPanelVendorContactUsRouteImport
      parentRoute: typeof vendorPanelVendorRoute
    }
    '/admin/cms/universities/': {
      id: '/admin/cms/universities/'
      path: '/cms/universities'
      fullPath: '/admin/cms/universities/'
      preLoaderRoute: typeof AdminCmsUniversitiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/trending-offers/': {
      id: '/admin/cms/trending-offers/'
      path: '/cms/trending-offers'
      fullPath: '/admin/cms/trending-offers/'
      preLoaderRoute: typeof AdminCmsTrendingOffersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/categories/': {
      id: '/admin/cms/categories/'
      path: '/cms/categories'
      fullPath: '/admin/cms/categories/'
      preLoaderRoute: typeof AdminCmsCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/brands/': {
      id: '/admin/cms/brands/'
      path: '/cms/brands'
      fullPath: '/admin/cms/brands/'
      preLoaderRoute: typeof AdminCmsBrandsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/banners/': {
      id: '/admin/cms/banners/'
      path: '/cms/banners'
      fullPath: '/admin/cms/banners/'
      preLoaderRoute: typeof AdminCmsBannersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendors/$vendorId/settings': {
      id: '/admin/vendors/$vendorId/settings'
      path: '/vendors/$vendorId/settings'
      fullPath: '/admin/vendors/$vendorId/settings'
      preLoaderRoute: typeof AdminVendorsVendorIdSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$studentId/settings': {
      id: '/admin/students/$studentId/settings'
      path: '/students/$studentId/settings'
      fullPath: '/admin/students/$studentId/settings'
      preLoaderRoute: typeof AdminStudentsStudentIdSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/universities/add': {
      id: '/admin/cms/universities/add'
      path: '/cms/universities/add'
      fullPath: '/admin/cms/universities/add'
      preLoaderRoute: typeof AdminCmsUniversitiesAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/categories/$categoryId': {
      id: '/admin/cms/categories/$categoryId'
      path: '/cms/categories/$categoryId'
      fullPath: '/admin/cms/categories/$categoryId'
      preLoaderRoute: typeof AdminCmsCategoriesCategoryIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/brands/add': {
      id: '/admin/cms/brands/add'
      path: '/cms/brands/add'
      fullPath: '/admin/cms/brands/add'
      preLoaderRoute: typeof AdminCmsBrandsAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/banners/add': {
      id: '/admin/cms/banners/add'
      path: '/cms/banners/add'
      fullPath: '/admin/cms/banners/add'
      preLoaderRoute: typeof AdminCmsBannersAddRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendors/$vendorId/settings/': {
      id: '/admin/vendors/$vendorId/settings/'
      path: '/'
      fullPath: '/admin/vendors/$vendorId/settings/'
      preLoaderRoute: typeof AdminVendorsVendorIdSettingsIndexRouteImport
      parentRoute: typeof AdminVendorsVendorIdSettingsRoute
    }
    '/admin/vendors/$vendorId/settings/offers': {
      id: '/admin/vendors/$vendorId/settings/offers'
      path: '/offers'
      fullPath: '/admin/vendors/$vendorId/settings/offers'
      preLoaderRoute: typeof AdminVendorsVendorIdSettingsOffersRouteImport
      parentRoute: typeof AdminVendorsVendorIdSettingsRoute
    }
    '/admin/vendors/$vendorId/settings/branding': {
      id: '/admin/vendors/$vendorId/settings/branding'
      path: '/branding'
      fullPath: '/admin/vendors/$vendorId/settings/branding'
      preLoaderRoute: typeof AdminVendorsVendorIdSettingsBrandingRouteImport
      parentRoute: typeof AdminVendorsVendorIdSettingsRoute
    }
  }
}

interface AdminVendorsVendorIdSettingsRouteChildren {
  AdminVendorsVendorIdSettingsBrandingRoute: typeof AdminVendorsVendorIdSettingsBrandingRoute
  AdminVendorsVendorIdSettingsOffersRoute: typeof AdminVendorsVendorIdSettingsOffersRoute
  AdminVendorsVendorIdSettingsIndexRoute: typeof AdminVendorsVendorIdSettingsIndexRoute
}

const AdminVendorsVendorIdSettingsRouteChildren: AdminVendorsVendorIdSettingsRouteChildren =
  {
    AdminVendorsVendorIdSettingsBrandingRoute:
      AdminVendorsVendorIdSettingsBrandingRoute,
    AdminVendorsVendorIdSettingsOffersRoute:
      AdminVendorsVendorIdSettingsOffersRoute,
    AdminVendorsVendorIdSettingsIndexRoute:
      AdminVendorsVendorIdSettingsIndexRoute,
  }

const AdminVendorsVendorIdSettingsRouteWithChildren =
  AdminVendorsVendorIdSettingsRoute._addFileChildren(
    AdminVendorsVendorIdSettingsRouteChildren,
  )

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTransactionsIdRoute: typeof AdminTransactionsIdRoute
  AdminCmsIndexRoute: typeof AdminCmsIndexRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
  AdminTransactionsIndexRoute: typeof AdminTransactionsIndexRoute
  AdminVendorsIndexRoute: typeof AdminVendorsIndexRoute
  AdminCmsBannersAddRoute: typeof AdminCmsBannersAddRoute
  AdminCmsBrandsAddRoute: typeof AdminCmsBrandsAddRoute
  AdminCmsCategoriesCategoryIdRoute: typeof AdminCmsCategoriesCategoryIdRoute
  AdminCmsUniversitiesAddRoute: typeof AdminCmsUniversitiesAddRoute
  AdminStudentsStudentIdSettingsRoute: typeof AdminStudentsStudentIdSettingsRoute
  AdminVendorsVendorIdSettingsRoute: typeof AdminVendorsVendorIdSettingsRouteWithChildren
  AdminCmsBannersIndexRoute: typeof AdminCmsBannersIndexRoute
  AdminCmsBrandsIndexRoute: typeof AdminCmsBrandsIndexRoute
  AdminCmsCategoriesIndexRoute: typeof AdminCmsCategoriesIndexRoute
  AdminCmsTrendingOffersIndexRoute: typeof AdminCmsTrendingOffersIndexRoute
  AdminCmsUniversitiesIndexRoute: typeof AdminCmsUniversitiesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTransactionsIdRoute: AdminTransactionsIdRoute,
  AdminCmsIndexRoute: AdminCmsIndexRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
  AdminTransactionsIndexRoute: AdminTransactionsIndexRoute,
  AdminVendorsIndexRoute: AdminVendorsIndexRoute,
  AdminCmsBannersAddRoute: AdminCmsBannersAddRoute,
  AdminCmsBrandsAddRoute: AdminCmsBrandsAddRoute,
  AdminCmsCategoriesCategoryIdRoute: AdminCmsCategoriesCategoryIdRoute,
  AdminCmsUniversitiesAddRoute: AdminCmsUniversitiesAddRoute,
  AdminStudentsStudentIdSettingsRoute: AdminStudentsStudentIdSettingsRoute,
  AdminVendorsVendorIdSettingsRoute:
    AdminVendorsVendorIdSettingsRouteWithChildren,
  AdminCmsBannersIndexRoute: AdminCmsBannersIndexRoute,
  AdminCmsBrandsIndexRoute: AdminCmsBrandsIndexRoute,
  AdminCmsCategoriesIndexRoute: AdminCmsCategoriesIndexRoute,
  AdminCmsTrendingOffersIndexRoute: AdminCmsTrendingOffersIndexRoute,
  AdminCmsUniversitiesIndexRoute: AdminCmsUniversitiesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface vendorPanelVendorRouteChildren {
  vendorPanelVendorContactUsRoute: typeof vendorPanelVendorContactUsRoute
  vendorPanelVendorDashboardRoute: typeof vendorPanelVendorDashboardRoute
  vendorPanelVendorPinRoute: typeof vendorPanelVendorPinRoute
}

const vendorPanelVendorRouteChildren: vendorPanelVendorRouteChildren = {
  vendorPanelVendorContactUsRoute: vendorPanelVendorContactUsRoute,
  vendorPanelVendorDashboardRoute: vendorPanelVendorDashboardRoute,
  vendorPanelVendorPinRoute: vendorPanelVendorPinRoute,
}

const vendorPanelVendorRouteWithChildren =
  vendorPanelVendorRoute._addFileChildren(vendorPanelVendorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRoute,
  FullstackDevRoute: FullstackDevRoute,
  InternshipsRoute: InternshipsRoute,
  MobileInternRoute: MobileInternRoute,
  OldHomeRoute: OldHomeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  authLoginRoute: authLoginRoute,
  authUnauthorizedRoute: authUnauthorizedRoute,
  vendorPanelVendorRoute: vendorPanelVendorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
